# Generated by Django 4.1.2 on 2022-10-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='id',
        ),
        migrations.AlterField(
            model_name='location',
            name='employee_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
