# Generated by Django 4.1.2 on 2022-10-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_remove_location_id_alter_location_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='employee_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=40),
        ),
    ]
